global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Logging;
global using Infrastructure.Options;
global using Infrastructure.Payments.Line.Models;
global using eShopX.Application.Interfaces;
global using eShopX.Application.Interfaces.Repositories;
