// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(EShopContext))]
    [Migration("20260316012833_initialize")]
    partial class initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eShopX.Domain.Aggregates.Carts.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("所屬使用者 ID");

                    b.HasKey("Id");

                    b.ToTable("Carts", t =>
                        {
                            t.HasComment("購物車（每位使用者一個）");
                        });
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Carts.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid")
                        .HasComment("所屬購物車 ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasComment("數量");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasComment("商品 SKU ID");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("CartItems", t =>
                        {
                            t.HasComment("購物車項目");
                        });
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("分類名稱（唯一）");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", t =>
                        {
                            t.HasComment("商品分類");
                        });
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("訂單狀態（待付款、已付款、已出貨、已完成）");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("下單使用者 ID");

                    b.HasKey("Id");

                    b.ToTable("Orders", t =>
                        {
                            t.HasComment("訂單主表");
                        });
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasComment("所屬訂單 ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasComment("購買數量");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasComment("下單時的 SKU ID");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", t =>
                        {
                            t.HasComment("訂單明細");
                        });
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Method")
                        .HasColumnType("integer")
                        .HasComment("付款方式（LinePay、PayPal、ECPay 等）");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasComment("關聯訂單 ID");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("實際付款完成時間");

                    b.Property<string>("PaymentUrl")
                        .HasColumnType("text")
                        .HasComment("付款頁面網址（由金流方產生）");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("付款狀態（待付款、已付款、失敗）");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text")
                        .HasComment("第三方金流交易序號");

                    b.HasKey("Id");

                    b.ToTable("Payments", t =>
                        {
                            t.HasComment("付款記錄");
                        });
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Audience")
                        .HasColumnType("integer")
                        .HasComment("適用客群（男、女、中性）");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasComment("所屬分類 ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("商品描述");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasComment("是否上架販售");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("商品名稱");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products", t =>
                        {
                            t.HasComment("商品主表");
                        });
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Products.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasComment("是否為主圖");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasComment("所屬款式 ID");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Cloudinary Public ID，用於更新或刪除");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasComment("排序順序（由小到大）");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("圖片網址");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("ProductImages", t =>
                        {
                            t.HasComment("商品圖片");
                        });
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Products.ProductSku", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasComment("所屬款式 ID");

                    b.Property<Guid?>("SizeId")
                        .HasColumnType("uuid")
                        .HasComment("所屬尺寸 ID（無尺寸商品為 null）");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer")
                        .HasComment("目前庫存數量");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("ProductSkus", t =>
                        {
                            t.HasComment("商品 SKU（款式 × 尺寸的最小庫存單位）");
                        });
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Products.ProductTag", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasComment("商品 ID");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasComment("標籤 ID");

                    b.HasKey("ProductId", "TagId");

                    b.ToTable("ProductTags", t =>
                        {
                            t.HasComment("商品與標籤的對應關係");
                        });
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Products.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("顏色名稱");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasComment("所屬商品 ID");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants", t =>
                        {
                            t.HasComment("商品款式（依顏色區分）");
                        });
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Shipments.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogisticsId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("綠界物流訂單編號");

                    b.Property<string>("LogisticsStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("物流狀態代碼（來自綠界回調）");

                    b.Property<string>("LogisticsStatusName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("物流狀態說明文字");

                    b.Property<int>("LogisticsSubType")
                        .HasColumnType("integer")
                        .HasComment("物流子類型（FAMIC2C、UNIMARTC2C、TCAT 等）");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasComment("關聯訂單 ID");

                    b.Property<string>("ShipmentType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("UpdateStatusDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("最後物流狀態更新時間");

                    b.HasKey("Id");

                    b.ToTable("Shipments", t =>
                        {
                            t.HasComment("物流出貨記錄（TPH：CVS 超取 / Home 宅配）");
                        });

                    b.HasDiscriminator<string>("ShipmentType").HasValue("Shipment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Sizes.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("尺寸名稱（S、M、L、XL 等）");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("尺寸分類（衣服、鞋子等）");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Sizes", t =>
                        {
                            t.HasComment("尺寸選項");
                        });
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("標籤名稱（唯一）");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("標籤類型（材質、風格、季節等）");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", t =>
                        {
                            t.HasComment("商品標籤");
                        });
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Token 到期時間");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasComment("是否已被撤銷");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Token 值（唯一）");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("所屬使用者 ID");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshTokens", t =>
                        {
                            t.HasComment("使用者 Refresh Token");
                        });
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("電子信箱（唯一）");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("顯示名稱");

                    b.Property<int>("Roles")
                        .HasColumnType("integer")
                        .HasComment("角色旗標（Flags enum，可複選）");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasComment("使用者主表");
                        });
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Users.UserAuthProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasComment("本地登入的雜湊密碼（第三方登入為 null）");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasComment("登入提供者（Local、Google、Line）");

                    b.Property<string>("ProviderUserId")
                        .HasColumnType("text")
                        .HasComment("第三方平台的使用者識別碼（sub）");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("所屬使用者 ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAuthProviders", t =>
                        {
                            t.HasComment("使用者登入方式（本地密碼 / 第三方 OAuth）");
                        });
                });

            modelBuilder.Entity("eShopX.Domain.Outbox.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("事件類型名稱（如 PaymentPaidEvent）");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("事件序列化內容（JSON）");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("事件成功處理的時間");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasComment("已重試次數（上限 3 次後標記為 Failed）");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("處理狀態（Pending、Processed、Failed）");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("OutboxEvents", t =>
                        {
                            t.HasComment("Outbox 事件佇列（保證至少一次送出 Domain Event）");
                        });
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Shipments.CVSShipment", b =>
                {
                    b.HasBaseType("eShopX.Domain.Aggregates.Shipments.Shipment");

                    b.Property<string>("CVSPaymentNo")
                        .HasColumnType("text")
                        .HasComment("超商繳費代碼（貨到付款時使用）");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("超商門市代號");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("超商門市名稱");

                    b.HasDiscriminator().HasValue("CVS");
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Shipments.HomeShipment", b =>
                {
                    b.HasBaseType("eShopX.Domain.Aggregates.Shipments.Shipment");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("收件詳細地址");

                    b.Property<string>("BookingNote")
                        .HasColumnType("text")
                        .HasComment("宅配備註（預約時段等）");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("收件地址郵遞區號");

                    b.HasDiscriminator().HasValue("Home");
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Carts.CartItem", b =>
                {
                    b.HasOne("eShopX.Domain.Aggregates.Carts.Cart", null)
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Orders.Order", b =>
                {
                    b.OwnsOne("eShopX.Domain.ValueObjects.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalAmount")
                                .HasComment("訂單總金額");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("TotalAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Orders.OrderItem", b =>
                {
                    b.HasOne("eShopX.Domain.Aggregates.Orders.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("eShopX.Domain.ValueObjects.Money", "TotalPrice", b1 =>
                        {
                            b1.Property<Guid>("OrderItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalPrice")
                                .HasComment("該明細小計（單價 × 數量）");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("OrderItems");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.OwnsOne("eShopX.Domain.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("OrderItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("UnitPrice")
                                .HasComment("下單當下的單價快照");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("OrderItems");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.OwnsOne("eShopX.Domain.ValueObjects.ProductSnapshot", "Snapshot", b1 =>
                        {
                            b1.Property<Guid>("OrderItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Color")
                                .HasComment("下單當下的顏色快照");

                            b1.Property<string>("ProductName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ProductName")
                                .HasComment("下單當下的商品名稱快照");

                            b1.Property<string>("Size")
                                .HasColumnType("text")
                                .HasColumnName("Size")
                                .HasComment("下單當下的尺寸快照");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("OrderItems");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("Snapshot")
                        .IsRequired();

                    b.Navigation("TotalPrice")
                        .IsRequired();

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Payments.Payment", b =>
                {
                    b.OwnsOne("eShopX.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("Amount")
                                .HasComment("付款金額");

                            b1.HasKey("PaymentId");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Products.ProductImage", b =>
                {
                    b.HasOne("eShopX.Domain.Aggregates.Products.ProductVariant", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Products.ProductSku", b =>
                {
                    b.HasOne("eShopX.Domain.Aggregates.Products.ProductVariant", null)
                        .WithMany("Skus")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("eShopX.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("ProductSkuId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("Price")
                                .HasComment("售價");

                            b1.HasKey("ProductSkuId");

                            b1.ToTable("ProductSkus");

                            b1.WithOwner()
                                .HasForeignKey("ProductSkuId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Products.ProductTag", b =>
                {
                    b.HasOne("eShopX.Domain.Aggregates.Products.Product", null)
                        .WithMany("Tags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Products.ProductVariant", b =>
                {
                    b.HasOne("eShopX.Domain.Aggregates.Products.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Users.User", b =>
                {
                    b.OwnsOne("eShopX.Domain.Aggregates.Users.Avatar", "Avatar", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PublicId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasComment("Cloudinary Public ID");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasComment("頭像圖片網址");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Users.UserAuthProvider", b =>
                {
                    b.HasOne("eShopX.Domain.Aggregates.Users.User", null)
                        .WithMany("AuthProviders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Shipments.CVSShipment", b =>
                {
                    b.OwnsOne("eShopX.Domain.ValueObjects.ReceiverInfo", "Receiver", b1 =>
                        {
                            b1.Property<Guid>("CVSShipmentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CellPhone")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("ReceiverPhone")
                                .HasComment("收件人手機號碼");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("ReceiverName")
                                .HasComment("收件人姓名");

                            b1.HasKey("CVSShipmentId");

                            b1.ToTable("Shipments");

                            b1.WithOwner()
                                .HasForeignKey("CVSShipmentId");
                        });

                    b.Navigation("Receiver")
                        .IsRequired();
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Shipments.HomeShipment", b =>
                {
                    b.OwnsOne("eShopX.Domain.ValueObjects.ReceiverInfo", "Receiver", b1 =>
                        {
                            b1.Property<Guid>("HomeShipmentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CellPhone")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("ReceiverPhone")
                                .HasComment("收件人手機號碼");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("ReceiverName")
                                .HasComment("收件人姓名");

                            b1.HasKey("HomeShipmentId");

                            b1.ToTable("Shipments");

                            b1.WithOwner()
                                .HasForeignKey("HomeShipmentId");
                        });

                    b.Navigation("Receiver")
                        .IsRequired();
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Carts.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Orders.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Products.Product", b =>
                {
                    b.Navigation("Tags");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Products.ProductVariant", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Skus");
                });

            modelBuilder.Entity("eShopX.Domain.Aggregates.Users.User", b =>
                {
                    b.Navigation("AuthProviders");
                });
#pragma warning restore 612, 618
        }
    }
}
