services:
  eshopx-postgres:
    image: postgres:18
    container_name: eshopx-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eShopX
      PGDATA: /var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  eshopx-redis:
    image: redis:8.4
    container_name: eshopx-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command:
      [
        "redis-server",
        "--requirepass", "redis123",
        "--appendonly", "yes"
      ]
    restart: unless-stopped
    
  broker:
      image: apache/kafka:latest
      container_name: broker
      environment:
        KAFKA_NODE_ID: 1
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.65.4:9092
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@192.168.65.4:9093
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_NUM_PARTITIONS: 3
        
  api:
    build:
      context: .
      dockerfile: src/eShopX.Api/Dockerfile
    container_name: eshopx-api
    depends_on:
      - eshopx-postgres
      - eshopx-redis
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5177
      ConnectionStrings__PostgreSQL: Host=eshopx-postgres;Port=5432;Username=user;Password=password;Database=eShopX
      ConnectionStrings__Redis: eshopx-redis:6379,password=redis123,defaultDatabase=0
      Jwt__SecretKey: ${JWT_SECRET_KEY:-}
      Jwt__RefreshTokenExpirationDays: ${JWT_REFRESH_DAYS:-7}
      Jwt__Issuer: ${JWT_ISSUER:-eShopX}
      Jwt__Audience: ${JWT_AUDIENCE:-eShopX-Users}
      Jwt__AccessTokenExpirationMinutes: ${JWT_ACCESS_MINUTES:-60}
      Mail__UseStartTls: ${MAIL_USE_STARTTLS:-true}
      Mail__UseSsl: ${MAIL_USE_SSL:-false}
      Mail__UserName: ${MAIL_USERNAME:-}
      Mail__SmtpPort: ${MAIL_SMTP_PORT:-587}
      Mail__SmtpHost: ${MAIL_SMTP_HOST:-smtp.gmail.com}
      Mail__Password: ${MAIL_PASSWORD:-}
      Mail__FromName: ${MAIL_FROM_NAME:-eShopX}
      Mail__FromEmail: ${MAIL_FROM_EMAIL:-}
      PayPal__PublicBaseUrl: ${PAYPAL_PUBLIC_BASE_URL:-}
      PayPal__FrontendBaseUrl: ${PAYPAL_FRONTEND_BASE_URL:-}
      PayPal__ClientSecret: ${PAYPAL_CLIENT_SECRET:-}
      PayPal__ClientId: ${PAYPAL_CLIENT_ID:-}
      PayPal__BaseUrl: ${PAYPAL_BASE_URL:-https://api-m.sandbox.paypal.com}
      LinePay__PublicBaseUrl: ${LINEPAY_PUBLIC_BASE_URL:-}
      LinePay__FrontendBaseUrl: ${LINEPAY_FRONTEND_BASE_URL:-}
      LinePay__ChannelSecret: ${LINEPAY_CHANNEL_SECRET:-}
      LinePay__ChannelId: ${LINEPAY_CHANNEL_ID:-}
      LinePay__BaseUrl: ${LINEPAY_BASE_URL:-https://sandbox-api-pay.line.me}
      LineAuth__RedirectUri: ${LINEAUTH_REDIRECT_URI:-}
      LineAuth__ChannelSecret: ${LINEAUTH_CHANNEL_SECRET:-}
      LineAuth__ChannelId: ${LINEAUTH_CHANNEL_ID:-}
      GoogleAuth__RedirectUrl: ${GOOGLE_REDIRECT_URL:-}
      GoogleAuth__ClientSecret: ${GOOGLE_CLIENT_SECRET:-}
      GoogleAuth__ClientId: ${GOOGLE_CLIENT_ID:-}
      Cloudinary__CloudName: ${CLOUDINARY_CLOUD_NAME:-}
      Cloudinary__ApiSecret: ${CLOUDINARY_API_SECRET:-}
      Cloudinary__ApiKey: ${CLOUDINARY_API_KEY:-}
    ports:
      - "5177:5177"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5177/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  web:
    build:
      context: src/eShopX.Web
      dockerfile: Dockerfile
    container_name: eshopx-web
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8080:80"
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.0
    container_name: eshopx-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  pgdata:
    driver: local
  redis_data:
    driver: local
  es_data:
    driver: local
