@startuml
class CartItem <<sealed>> {
    + Quantity : int <<get>>
    - CartItem()
    + {static} Create(cartId:Guid, skuId:Guid, quantity:int) : CartItem
    + UpdateQuantity(quantity:int) : void
}
Entity <|-- CartItem
CartItem --> "CartId" Guid
CartItem --> "SkuId" Guid
@enduml
