@startuml
class Cart <<sealed>> {
    - Cart()
    + {static} Create(userId:Guid) : Cart
    + AddItem(skuId:Guid, quantity:int) : void
    + RemoveItem(skuId:Guid) : void
    + UpdateQuantity(skuId:Guid, quantity:int) : void
    + Clear() : void
}
class "List`1"<T> {
}
class "IReadOnlyList`1"<T> {
}
AggregateRoot <|-- Cart
Cart o-> "_items<CartItem>" "List`1"
Cart --> "UserId" Guid
Cart --> "CreatedAt" DateTime
Cart --> "Items<CartItem>" "IReadOnlyList`1"
@enduml
