@startuml
class CVSShipment <<sealed>> {
    + StoreId : string <<get>>
    + StoreName : string <<get>>
    + CVSPaymentNo : string? <<get>>
    - CVSShipment()
    + {static} Create(orderId:Guid, logisticsId:string, logisticsSubType:LogisticsSubType, receiver:ReceiverInfo, storeId:string, storeName:string) : CVSShipment
    + UpdateCVSPaymentNo(cvsPaymentNo:string) : void
}
Shipment <|-- CVSShipment
CVSShipment o-> "Receiver" ReceiverInfo
@enduml
