@startuml
class HomeShipment <<sealed>> {
    + ZipCode : string <<get>>
    + Address : string <<get>>
    + BookingNote : string? <<get>>
    - HomeShipment()
    + {static} Create(orderId:Guid, logisticsId:string, logisticsSubType:LogisticsSubType, receiver:ReceiverInfo, zipCode:string, address:string, bookingNote:string?) : HomeShipment
}
Shipment <|-- HomeShipment
HomeShipment o-> "Receiver" ReceiverInfo
@enduml
