@startuml
abstract class Shipment {
    + LogisticsId : string <<get>> <<protected set>>
    + LogisticsStatus : string <<get>> <<protected set>>
    + LogisticsStatusName : string <<get>> <<protected set>>
    + AssignRealLogisticsId(logisticsId:string) : void
    + UpdateStatus(logisticsStatus:string, logisticsStatusName:string, updateStatusDate:DateTime) : void
    + MarkAsCompleted() : void
}
AggregateRoot <|-- Shipment
Shipment --> "OrderId" Guid
Shipment --> "LogisticsSubType" LogisticsSubType
Shipment --> "UpdateStatusDate" DateTime
Shipment --> "CreatedAt" DateTime
@enduml
