@startuml
class Product <<sealed>> {
    + Name : string <<get>>
    + Description : string? <<get>>
    + IsActive : bool <<get>>
    - Product()
    + {static} Create(name:string, description:string?, audience:Audience?, categoryId:Guid) : Product
    + AddVariant(color:string) : ProductVariant
    + AddTag(tagId:Guid) : void
    + SyncTags(tagIds:IReadOnlyList<Guid>) : void
    + RemoveVariant(variantId:Guid) : void
    + Update(name:string, description:string?, audience:Audience?, categoryId:Guid) : void
    + Publish() : void
    + Unpublish() : void
    + Delete() : void
}
class "List`1"<T> {
}
class "IReadOnlyList`1"<T> {
}
AggregateRoot <|-- Product
Product o-> "_variants<ProductVariant>" "List`1"
Product o-> "_tags<ProductTag>" "List`1"
Product --> "Audience" Audience
Product --> "CategoryId" Guid
Product --> "CreatedAt" DateTime
Product --> "UpdatedAt" DateTime
Product --> "Variants<ProductVariant>" "IReadOnlyList`1"
Product --> "Tags<ProductTag>" "IReadOnlyList`1"
@enduml
