@startuml
class UserAuthProvider <<sealed>> {
    + ProviderUserId : string? <<get>>
    + PasswordHash : string? <<get>>
    - UserAuthProvider()
    + {static} Create(userId:Guid, provider:Provider, providerUserId:string?, passwordHash:string?) : UserAuthProvider
}
Entity <|-- UserAuthProvider
UserAuthProvider --> "UserId" Guid
UserAuthProvider --> "Provider" Provider
UserAuthProvider --> "CreatedAt" DateTime
@enduml
