apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eshopx-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshopx-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshopx-postgres
  template:
    metadata:
      labels:
        app: eshopx-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: eshopx-postgres-secret
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/postgresql/18/main
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: eshopx-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: eshopx-postgres
spec:
  selector:
    app: eshopx-postgres
  ports:
    - port: 5432
      targetPort: 5432
