global using System.Net.Mime;
global using CoreMesh.Dispatching.Abstractions;
global using CoreMesh.Endpoints;
global using CoreMesh.Result;
global using CoreMesh.Result.Extensions;
global using Infrastructure;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Routing;
