@startuml
abstract class AggregateRoot {
    # RaiseDomainEvent(domainEvent:INotification) : void
    + ClearDomainEvents() : void
}
class "List`1"<T> {
}
class "IReadOnlyList`1"<T> {
}
AggregateRoot --> "Id" Guid
AggregateRoot o-> "_domainEvents<INotification>" "List`1"
AggregateRoot --> "DomainEvents<INotification>" "IReadOnlyList`1"
@enduml
