@startuml
' Aggregate: Categories
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam ArrowColor #555555
skinparam ClassBorderColor #888888
hide empty members

class Category <<AggregateRoot>> #D4E6F1 {
  +Name: string
  +CreatedAt: DateTime
  +UpdatedAt: DateTime
  ..
  +Rename()
}

' --- Inheritance ---
Category --|> AggregateRoot

' --- Composition ---

' --- Domain Events ---

@enduml