@startuml
!include ./AggregateRoot.puml
!include ./Entity.puml
!include ./Shipments/LogisticsSubType.puml
!include ./Shipments/HomeShipment.puml
!include ./Shipments/CVSShipment.puml
!include ./Shipments/Shipment.puml
!include ./Payments/PaymentStatus.puml
!include ./Payments/Payment.puml
!include ./Payments/PaymentMethod.puml
!include ./Products/ProductTag.puml
!include ./Products/ProductSku.puml
!include ./Products/ProductImage.puml
!include ./Products/Audience.puml
!include ./Products/ProductVariant.puml
!include ./Products/Product.puml
!include ./Tags/Tag.puml
!include ./Tags/TagType.puml
!include ./Carts/Cart.puml
!include ./Carts/CartItem.puml
!include ./Sizes/Size.puml
!include ./Sizes/SizeType.puml
!include ./Users/UserAuthProvider.puml
!include ./Users/Role.puml
!include ./Users/Avatar.puml
!include ./Users/RefreshToken.puml
!include ./Users/User.puml
!include ./Users/Provider.puml
!include ./Orders/Order.puml
!include ./Orders/OrderStatus.puml
!include ./Orders/OrderItem.puml
!include ./Categories/Category.puml
!include ./Shipments/Events/ShipmentCompletedEvent.puml
!include ./Payments/Events/PaymentPaidEvent.puml
!include ./Payments/Events/PaymentFailedEvent.puml
!include ./Products/Events/ProductUpdatedEvent.puml
!include ./Products/Events/ProductCreatedEvent.puml
!include ./Products/Events/ProductDeletedEvent.puml
!include ./Orders/Events/OrderShippedEvent.puml
@enduml
