apiVersion: v1
kind: Secret
metadata:
  name: eshopx-api-secret
type: Opaque
stringData:
  ASPNETCORE_URLS: "http://0.0.0.0:5177"
  ConnectionStrings__PostgreSQL: "Host=eshopx-postgres;Port=5432;Username=user;Password=password;Database=eShopX"
  ConnectionStrings__Redis: "eshopx-redis:6379,password=redis123,defaultDatabase=0"
  Jwt__SecretKey: "oBapaL9FBUwUzQdVnAbjPT7wua7Wk46oBt2d8mBccsw"
  Jwt__RefreshTokenExpirationDays: "7"
  Jwt__Issuer: "eShopX"
  Jwt__Audience: "eShopX-Users"
  Jwt__AccessTokenExpirationMinutes: "60"
  GoogleAuth__RedirectUrl: "http://localhost:4200/auth/google/callback"
  GoogleAuth__ClientSecret: "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"
  GoogleAuth__ClientId: "81840048967-d6k4331ks8sllq08qac4morq5877t843.apps.googleusercontent.com"
  LineAuth__RedirectUri: "http://localhost:4200/auth/line/callback"
  LineAuth__ChannelSecret: "c6cd86985db306f9f36f97c5264e4058"
  LineAuth__ChannelId: "2009031910"
  LinePay__PublicBaseUrl: "https://eshop-x.com"
  LinePay__FrontendBaseUrl: "http://localhost:4200"
  LinePay__ChannelSecret: "2017c295cc6c57271b7c02fe4960166d"
  LinePay__ChannelId: "2009032765"
  LinePay__BaseUrl: "https://sandbox-api-pay.line.me"
  PayPal__PublicBaseUrl: "https://eshop-x.com"
  PayPal__FrontendBaseUrl: "http://localhost:4200"
  PayPal__ClientSecret: "EKUGHyYvCdMoQXcTBuU5MdTBfTgHg6MvJjNYN7ROXif4xUraCghxWPgPIAxPCxYSzDY6XqGOs-eHBsd3"
  PayPal__ClientId: "AbhORxguKI20EAnGPkqb-4rbZMblOZNZVnEOLRl-wtXxBqHyDp9lBQbP6JiDioPSLfkJbx9TzlnzNwvZ"
  PayPal__BaseUrl: "https://api-m.sandbox.paypal.com"
  Mail__UseStartTls: "true"
  Mail__UseSsl: "false"
  Mail__UserName: "a880617c@gmail.com"
  Mail__SmtpPort: "587"
  Mail__SmtpHost: "smtp.gmail.com"
  Mail__Password: "yfks mgxw pirs iisq"
  Mail__FromName: "eShopX"
  Mail__FromEmail: "a880617c@gmail.com"
  Kafka__OutboxEventTopic: "outbox-events"
  Kafka__Consumer__BootstrapServers: "eshopx-kafka:9092"
  Kafka__Consumer__GroupId: "eshopx-api"
  Kafka__Consumer__AutoOffsetReset: "Earliest"
  Kafka__Consumer__EnableAutoCommit: "false"
  Kafka__Producer__BootstrapServers: "eshopx-kafka:9092"
  Kafka__Producer__Acks: "All"
  Kafka__Producer__EnableIdempotence: "true"
  Cloudinary__CloudName: "decgap2tl"
  Cloudinary__ApiSecret: "MYv6caxbTWM9nGfvuDZvTRlTR8Q"
  Cloudinary__ApiKey: "839847297376569"
  Cors__AllowedOrigins: "https://eshop-x.com"
