name: Build and Push Images

on:
  push:
    branches: ["main"]

jobs:
  ef-migrate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      ConnectionStrings__PostgreSQL: ${{ vars.CONNECTIONSTRINGS__POSTGRESQL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Generate migration script
        run: |
          dotnet restore src/eShopX.Api/eShopX.Api.csproj
          dotnet build src/eShopX.Api/eShopX.Api.csproj -c Release
          dotnet tool install --global dotnet-ef
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet ef migrations script --idempotent --no-build --configuration Release \
            --project src/Infrastructure/Infrastructure.csproj \
            --startup-project src/eShopX.Api/eShopX.Api.csproj \
            -o migrations.sql

      - name: Upload migrations artifact
        uses: actions/upload-artifact@v4
        with:
          name: migrations
          path: migrations.sql

      - name: Upload k8s manifests
        uses: actions/upload-artifact@v4
        with:
          name: k8s
          path: k8s/

  build:
    needs: ef-migrate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push API
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/eShopX.Api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/eshopx-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/eshopx-api:${{ github.sha }}

      - name: Build & Push Web
        uses: docker/build-push-action@v6
        with:
          context: src/eShopX.Web
          file: src/eShopX.Web/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/eshopx-web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/eshopx-web:${{ github.sha }}

  migrate:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Download migrations artifact
        uses: actions/download-artifact@v7
        with:
          name: migrations
          path: .
      - name: Create ConfigMap
        run: |
          kubectl delete configmap db-migrations --ignore-not-found
          kubectl create configmap db-migrations --from-file=migrations.sql
      - name: Apply migration
        run: |
          kubectl run psql-migrate --rm -i --restart=Never \
            --image=postgres:18 \
            --overrides='{
              "spec": {
                "containers": [{
                  "name": "psql",
                  "image": "postgres:18",
                  "command": ["sh","-c","psql -h eshopx-postgres -U user -d eShopX -f /migrations/migrations.sql"],
                  "volumeMounts": [{"name":"migrations","mountPath":"/migrations"}],
                  "env": [{"name":"PGPASSWORD","value":"password"}]
                }],
                "volumes": [{"name":"migrations","configMap":{"name":"db-migrations"}}]
              }
            }'

  deploy:
    needs: migrate
    runs-on: self-hosted
    steps:
      - name: Download k8s manifests
        uses: actions/download-artifact@v4
        with:
          name: k8s
          path: k8s
      - name: Apply manifests
        run: kubectl apply -f k8s/
