@startuml
class Payment <<sealed>> {
    + TransactionId : string? <<get>>
    + PaymentUrl : string? <<get>>
    - Payment()
    + {static} Create(orderId:Guid, method:PaymentMethod, amount:Money, paymentUrl:string?) : Payment
    + SetPaymentUrl(url:string) : void
    + MarkAsPaid(transactionId:string) : void
    + MarkAsFailed() : void
}
AggregateRoot <|-- Payment
Payment --> "OrderId" Guid
Payment --> "Method" PaymentMethod
Payment --> "Status" PaymentStatus
Payment o-> "Amount" Money
Payment --> "PaidAt" DateTime
Payment --> "CreatedAt" DateTime
@enduml
